# config.yaml
scenario_name: "T5C5"
player_side: "T"
scenario_script_folder_name: "MyNet_episode_battle"
debug_mode: false
agent:
  ac_name: "1101 Cheng Kung [Perry Class, Kuang Hua I]"
  target_name: "target"
  